version: '3'
services:
  db_source_of_truth:
    container_name: db_truth
    build:
      context: .
      dockerfile: ./Dockerfile.truth_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
